#!/bin/bash

## overrule where needed

#export AWX_SRC_SECRET_KEY='awxsecret'
#export AWX_SRC_DBNAME='awx'
#export AWX_SRC_DBUSER='awx'
#export AWX_SRC_DBPASSWORD='awxpass'
#export AWX_SRC_DBHOST='localhost'
#export AWX_SRC_DBPORT='5432'
#export AWX_SRC_DATA_CACHE='awx-data.pickle'
#export AWX_DST_SECRET_KEY='awxsecret'
#export AWX_DST_DBNAME='awx'
#export AWX_DST_DBUSER='awx'
#export AWX_DST_DBPASSWORD='awxpass'
#export AWX_DST_DBHOST='localhost'
#export AWX_DST_DBPORT='5433'

./awx-migrate $0
